data_root:
  Darwin: /Users/heydar/Work/void/projects/pt
  Linux: /network/basestorage/data/pt

project: snippets

templates:
  model: 'model.pt'
  ema_model: 'ema_model.pt'
  snapshots: 'snapshots/model_snapshot_%d.pt'

params :
  timesteps: 300
  batch_size: 32
  image_size: 128

save_snapshots: false
transform: 'dt_att'
dataset: 'celeba' 
  
model : 
  name: 'unet_att'
  params :
    num_attributes: 40

