
api:
  server: 'http://192.168.0.2:8080' 

trainer:
  optimizer :
    name: 'SGD'
    lr: 0.03
    momentum: 0.9
    decay: 1e-5
  nepoch: 100
  use_ema: false
  batch_size: 64
  accumulate_batch_size: 256
  eval_batch_size_multiplier: 2
